USE [master]
GO
/****** Object:  Database [OHD]    Script Date: 21/10/2021 12:08:43 SA ******/
CREATE DATABASE [OHD]
GO
ALTER DATABASE [OHD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OHD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OHD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OHD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OHD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OHD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OHD] SET ARITHABORT OFF 
GO
ALTER DATABASE [OHD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OHD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OHD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OHD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OHD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OHD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OHD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OHD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OHD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OHD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OHD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OHD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OHD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OHD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OHD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OHD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OHD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OHD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OHD] SET  MULTI_USER 
GO
ALTER DATABASE [OHD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OHD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OHD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OHD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OHD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OHD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [OHD] SET QUERY_STORE = OFF
GO
USE [OHD]
GO
/****** Object:  Table [dbo].[account]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[account](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL,
	[email] [varchar](255) NULL,
	[username] [varchar](255) NULL,
	[password] [varchar](255) NULL,
	[role_id] [int] NULL,
	[token] [varchar](255) NULL,
	[status] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[category]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[category](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL,
	[account_id] [int] NULL,
	[description] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[head_task]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[head_task](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[request_by_user_id] [int] NULL,
	[head_task_status] [varchar](255) NULL,
	[note] [varchar](max) NULL,
	[start_date] [datetime2](0) NULL,
	[end_date] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[request_by_user]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[request_by_user](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[start_date] [datetime2](0) NULL,
	[end_date] [datetime2](0) NULL,
	[request_priority_id] [int] NULL,
	[request_status_id] [int] NULL,
	[description] [varchar](255) NULL,
	[category_id] [int] NULL,
	[account_id] [int] NULL,
	[service_id] [int] NULL,
	[reason_close_request] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[request_priority]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[request_priority](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[request_status]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[request_status](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[role]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[role](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[service]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[service](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL,
	[category_id] [int] NULL,
	[description] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[user_task]    Script Date: 21/10/2021 12:08:43 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user_task](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[request_by_user_id] [int] NULL,
	[user_task_status] [varchar](255) NULL,
	[note] [varchar](max) NULL,
	[start_date] [datetime2](0) NULL,
	[end_date] [datetime2](0) NULL,
	[head_task_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[account]  WITH CHECK ADD FOREIGN KEY([role_id])
REFERENCES [dbo].[role] ([id])
GO
ALTER TABLE [dbo].[head_task]  WITH CHECK ADD FOREIGN KEY([request_by_user_id])
REFERENCES [dbo].[request_by_user] ([id])
GO
ALTER TABLE [dbo].[request_by_user]  WITH CHECK ADD FOREIGN KEY([account_id])
REFERENCES [dbo].[account] ([id])
GO
ALTER TABLE [dbo].[request_by_user]  WITH CHECK ADD FOREIGN KEY([category_id])
REFERENCES [dbo].[category] ([id])
GO
ALTER TABLE [dbo].[request_by_user]  WITH CHECK ADD FOREIGN KEY([request_status_id])
REFERENCES [dbo].[request_status] ([id])
GO
ALTER TABLE [dbo].[request_by_user]  WITH CHECK ADD FOREIGN KEY([request_priority_id])
REFERENCES [dbo].[request_priority] ([id])
GO
ALTER TABLE [dbo].[request_by_user]  WITH CHECK ADD FOREIGN KEY([service_id])
REFERENCES [dbo].[service] ([id])
GO
ALTER TABLE [dbo].[user_task]  WITH CHECK ADD FOREIGN KEY([head_task_id])
REFERENCES [dbo].[head_task] ([id])
GO
ALTER TABLE [dbo].[user_task]  WITH CHECK ADD FOREIGN KEY([request_by_user_id])
REFERENCES [dbo].[request_by_user] ([id])
GO
USE [master]
GO
ALTER DATABASE [OHD] SET  READ_WRITE 
GO